import 'package:flutter/material.dart';

const Color backGroundColor = Color(0xFFFFF4F6);
const Color secondaryWhiteColor = Color(0xFFFFFDFF);
const Color primaryPinkColor = Color(0xFFF7C2CB);
const Color secondaryAwashColor = Color(0xFFE5E5E5);
const Color secondaryPinkColor = Color(0xFFFFEFF2);
const Color primaryGreyColor = Color(0xFF7F7B75);
const Color primaryGreyColor2 = Color(0xFFDFDFDF);
const Color primaryGreenColor = Color(0xFF8CA899);
const Color secondaryGreenColor = Color(0xFFB8CCC1);
const Color pinkLightColor = Color(0xFFFFF4F6);
const Color primaryBlackColor = Color(0xFF2B2B2E);
const Color primaryAwashColor = Color(0xFFE5DCDD);
const Color secondaryBlackColor = Color(0xFF545353);
const Color secondaryBlackColor2 = Color(0xFF545351);
const Color primaryWhiteColor = Color(0xFFFFFFFF);
const Color secondaryWhiteColor2 = Color(0xFFF4F4F4);
const Color blackColor2 = Color(0xFF505050);
const Color blackColor57 = Color(0xFF555F57);
const Color lightGrey = Color(0xFF86857F);
const Color blackColor50 = Color(0xFF505050);
const Color blackColorA0 = Color(0xFFA0A0A0);
const Color blackColor77 = Color(0xFF7F7C77);
const Color blackColorD9 = Color(0xFFD9D9D9);
const Color blackColor97 = Color(0xFF9F9C97);
const Color greyEC = Color(0xFFECECEC);
const Color lightGreen = Color(0xFFB8CCC2);